---
editorconfig:
  - changed-files:
      - any-blob-to-any-file:
          - "**/.editorconfig"

document:
  - changed-files:
      - any-blob-to-any-file:
          - "**/*.md"
          - "**/*.txt"
          - "**/*.rst"
          - "LICENSE"

terraform:
  - changed-files:
      - any-blob-to-any-file:
          - ".github/actions/terraform**/action.yml"
          - ".github/workflows/terraform**.yml"

textlint:
  - changed-files:
      - any-blob-to-any-file:
          - "**/.textlint*"

yamllint:
  - changed-files:
      - any-blob-to-any-file:
          - "**/.yamllint"

markdownlint:
  - changed-files:
      - any-blob-to-any-file:
          - "**/.markdownlint*.json"

asdf:
  - changed-files:
      - any-blob-to-any-file: -"**/.tool-versions"

actionlint:
  - changed-files:
      - any-blob-to-any-file:
          - "**/.github/workflows/actionlint.yml"

CODEOWNERS:
  - changed-files:
      - any-blob-to-any-file:
          - "**/CODEOWNERS"
