editorconfig:
  - .editorconfig

document:
  - "**/*.md"
  - "**/*.txt"
  - "**/*.rst"
  - LICENSE

terraform:
  - .github/actions/terraform**/action.yml
  - .github/workflows/terraform**.yml

textlint:
  - "**/.textlint*"

yamllint:
  - "**/.yamllint"

markdownlint:
  - "**/.markdownlint*.json"

asdf:
  - "**/.tool-versions"

actionlint:
  - .github/workflows/actionlint.yml

CODEOWNERS:
  - CODEOWNERS
