---
editorconfig:
  - changed-files:
      - "**/.editorconfig"
# document:
#   - changed-files: ["**/*.md", "**/*.txt", "**/*.rst", "LICENSE"]

# terraform:
#   - changed-files:
#       [
#         ".github/actions/terraform**/action.yml",
#         ".github/workflows/terraform**.yml",
#       ]

# textlint:
#   - changed-files: ["**/.textlint*"]

# yamllint:
#   - changed-files: ["**/.yamllint"]

# markdownlint:
#   - changed-files: ["**/.markdownlint*.json"]

# asdf:
#   - changed-files: ["**/.tool-versions"]

# actionlint:
#   - changed-files: ["**/.github/workflows/actionlint.yml"]

# CODEOWNERS:
#   - changed-files: ["**/CODEOWNERS"]
