---
name: Labeler

on:
  pull_request:

jobs:
  auto-labeling:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
