---
name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: -a --show-diff-on-failure
